In [1]:
%matplotlib inline

In [2]:
import matplotlib.pyplot as plt

In [3]:
import numpy
import numpy as np
import pandas
import pandas as pd

In [6]:
import os, sys
print(os.getcwd() )
print( os.listdir( "../data/") )

/home/topolo/PropD/cuBlackDream/examples
['ex1data1.txt', 'ex1data2.txt']


In [9]:
ex1data1DF = pd.read_csv("../data/ex1data1.txt")
ex1data2DF = pd.read_csv("../data/ex1data2.txt")

In [21]:
Xyex1data1 = ex1data1DF.values
Xex1data1 = Xyex1data1[:,0]
yex1data1 = Xyex1data1[:,1]
Xyex1data2 = ex1data2DF.values
Xex1data2 = Xyex1data2[:,0:-1]
yex1data2 = Xyex1data2[:,-1]
print(Xex1data1.shape)
print(yex1data1.shape)
print(Xex1data2.shape)
print(yex1data2.shape)
Xex1data1 = np.vstack( Xex1data1 )
yex1data1 = np.vstack( yex1data1 )
yex1data2 = np.vstack( yex1data2 )
print(Xex1data1.shape)
print(yex1data1.shape)
print(Xex1data2.shape)
print(yex1data2.shape)

(96,)
(96,)
(46, 2)
(46,)
(96, 1)
(96, 1)
(46, 2)
(46, 1)


In [22]:
Theta=np.array([0.])
b = np.array([0.])

In [26]:
a1 = np.matmul( Xex1data1, Theta) + b
print(a1)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.]


In [32]:
res = np.vstack(a1) - yex1data1
print(np.hstack(res))

[ -9.1302  -13.662   -11.854    -6.8233  -11.886    -4.3483  -12.       -6.5987
  -3.8166   -3.2522  -15.505    -3.1551   -7.2258   -0.71618  -3.5129
  -5.3048   -0.56077  -3.6518   -5.3893   -3.1386  -21.767    -4.263
  -5.1875   -3.0825  -22.638   -13.501    -7.0467  -14.692   -24.147     1.22
  -5.9966  -12.134    -1.8495   -6.5426   -4.5623   -4.1164   -3.3928
 -10.117    -5.4974   -0.55657  -3.9115   -5.3854   -2.4406   -6.7318
  -1.0463   -5.1337   -1.844    -8.0043   -1.0179   -6.7504   -1.8396
  -4.2885   -4.9981   -1.4233    1.4211   -2.4756   -4.6042   -3.9624
  -5.4141   -5.1694    0.74279 -17.929   -12.054   -17.054    -4.8852
  -5.7442   -7.7754   -1.0173  -20.992    -6.6799   -4.0259   -1.2784
  -3.3411    2.6807   -0.29678  -3.8845   -5.7014   -6.7526   -2.0576
  -0.47953  -0.20421  -0.67861  -7.5435   -5.3436   -4.2415   -6.7981
  -0.92695  -0.152    -2.8214   -1.8451   -4.2959   -7.2029   -1.9869
  -0.14454  -9.0551   -0.61705]


In [33]:
np.matmul( np.hstack(res) , res)

array([ 5912.63190823])

In [37]:
0.5 * np.matmul( np.hstack(res) , res) / (float( Xex1data1.size ) )

array([ 30.79495786])

In [36]:
Xex1data1.size

96

In [39]:
np.matmul( np.hstack(res) , Xex1data1) / (float( Xex1data1.size ))

array([-64.88968277])

In [ ]:
def grad_desc_1( yhat, y , Theta, b, alpha): 
    res = yhat - y 